### Obtener el carrito
GET http://localhost:3000/api/cart
Content-Type: application/json
Cookie: next-auth.session-token=eyJhbGciOiJkaXIiLCJlbmMiOiJBMjU2Q0JDLUhTNTEyIiwia2lkIjoiVmdrVF9QT2JXUEtYTk8yem1MOUFoaHk2SmtZc01RRzFnWHdFYTdyWVhlUnpmT3M5Rl9UdE5fLTdManA5cFZVV2ZPYTROTUc5c2J4MXBSZlQ4UUphX2cifQ..cAhmW6YPTLhNxvYQSYguFQ.gXCkaUM6p_NJoVZoay0Dgii91TMMJ1-i7W9eiUPOjWt7jUxB3V-mcwCttHMcsVZf3sk2rR-bd7HjW1KbYHbtjAfgSDpJdZQCnLc4fgW-yglsIcRGNH66IN8HxPvOC14N6t92GfPwe6oIYyP9uP2mCGJh299rpeiWMj32wF9AlCw4gmrrab_NNZ3e2Zq063AAWRF-AZc0sxMl-K-4yesi11OscZrl0JsejM1HcKQkybIa9rhewpZ65Lc9c6WjoeYi4HeBc_I483paviAAwuslxPSwVUltBBXio3gcUzphCH3pzX2hq69ofqac1tZa8iau.T1zgzivacZw0DEHcaMp3GH4LzdbDycuDQa4mg4p4Sd0

### Agregar un producto al carrito
POST http://localhost:3000/api/cart
Content-Type: application/json
Cookie: next-auth.session-token=eyJhbGciOiJkaXIiLCJlbmMiOiJBMjU2Q0JDLUhTNTEyIiwia2lkIjoiVmdrVF9QT2JXUEtYTk8yem1MOUFoaHk2SmtZc01RRzFnWHdFYTdyWVhlUnpmT3M5Rl9UdE5fLTdManA5cFZVV2ZPYTROTUc5c2J4MXBSZlQ4UUphX2cifQ..cAhmW6YPTLhNxvYQSYguFQ.gXCkaUM6p_NJoVZoay0Dgii91TMMJ1-i7W9eiUPOjWt7jUxB3V-mcwCttHMcsVZf3sk2rR-bd7HjW1KbYHbtjAfgSDpJdZQCnLc4fgW-yglsIcRGNH66IN8HxPvOC14N6t92GfPwe6oIYyP9uP2mCGJh299rpeiWMj32wF9AlCw4gmrrab_NNZ3e2Zq063AAWRF-AZc0sxMl-K-4yesi11OscZrl0JsejM1HcKQkybIa9rhewpZ65Lc9c6WjoeYi4HeBc_I483paviAAwuslxPSwVUltBBXio3gcUzphCH3pzX2hq69ofqac1tZa8iau.T1zgzivacZw0DEHcaMp3GH4LzdbDycuDQa4mg4p4Sd0

{
  "productId": "product-1",
  "quantity": 2
}

### Actualizar la cantidad de un producto en el carrito
PUT http://localhost:3000/api/cart
Content-Type: application/json
Cookie: next-auth.session-token=eyJhbGciOiJkaXIiLCJlbmMiOiJBMjU2Q0JDLUhTNTEyIiwia2lkIjoiVmdrVF9QT2JXUEtYTk8yem1MOUFoaHk2SmtZc01RRzFnWHdFYTdyWVhlUnpmT3M5Rl9UdE5fLTdManA5cFZVV2ZPYTROTUc5c2J4MXBSZlQ4UUphX2cifQ..cAhmW6YPTLhNxvYQSYguFQ.gXCkaUM6p_NJoVZoay0Dgii91TMMJ1-i7W9eiUPOjWt7jUxB3V-mcwCttHMcsVZf3sk2rR-bd7HjW1KbYHbtjAfgSDpJdZQCnLc4fgW-yglsIcRGNH66IN8HxPvOC14N6t92GfPwe6oIYyP9uP2mCGJh299rpeiWMj32wF9AlCw4gmrrab_NNZ3e2Zq063AAWRF-AZc0sxMl-K-4yesi11OscZrl0JsejM1HcKQkybIa9rhewpZ65Lc9c6WjoeYi4HeBc_I483paviAAwuslxPSwVUltBBXio3gcUzphCH3pzX2hq69ofqac1tZa8iau.T1zgzivacZw0DEHcaMp3GH4LzdbDycuDQa4mg4p4Sd0

{
  "productId": "123",
  "quantity": 5
}

### Eliminar un producto del carrito
DELETE http://localhost:3000/api/cart
Content-Type: application/json
Cookie: next-auth.session-token=eyJhbGciOiJkaXIiLCJlbmMiOiJBMjU2Q0JDLUhTNTEyIiwia2lkIjoiVmdrVF9QT2JXUEtYTk8yem1MOUFoaHk2SmtZc01RRzFnWHdFYTdyWVhlUnpmT3M5Rl9UdE5fLTdManA5cFZVV2ZPYTROTUc5c2J4MXBSZlQ4UUphX2cifQ..cAhmW6YPTLhNxvYQSYguFQ.gXCkaUM6p_NJoVZoay0Dgii91TMMJ1-i7W9eiUPOjWt7jUxB3V-mcwCttHMcsVZf3sk2rR-bd7HjW1KbYHbtjAfgSDpJdZQCnLc4fgW-yglsIcRGNH66IN8HxPvOC14N6t92GfPwe6oIYyP9uP2mCGJh299rpeiWMj32wF9AlCw4gmrrab_NNZ3e2Zq063AAWRF-AZc0sxMl-K-4yesi11OscZrl0JsejM1HcKQkybIa9rhewpZ65Lc9c6WjoeYi4HeBc_I483paviAAwuslxPSwVUltBBXio3gcUzphCH3pzX2hq69ofqac1tZa8iau.T1zgzivacZw0DEHcaMp3GH4LzdbDycuDQa4mg4p4Sd0

{
  "productId": "product-1",
  "quantity": 2
}